---
title: "RWorksheet_Langreo#4a"
author: "Kea Joy Langreo"
date: "2024-10-29"
output: pdf_document
---


```{r}
#1
shoesize1 <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)
height1 <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0)
gender1 <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")

shoesize2 <- c(13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height2 <- c(77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender2 <- c("M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")

df <- data.frame(ShoeSize = c(shoesize1, shoesize2), Height = c(height1, height2), Gender = c(gender1, gender2))
df



#1a.
#The data is consists of the different shoe size with corresponding height and gender of the user.

#1b.
male_data <- subset(df, Gender == "M")
female_data <- subset(df, Gender == "F")

male_data
female_data

#1c.
shoesize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0)
mean_shoesize <- mean(shoesize)
mean_height <- mean(height)
mean_shoesize
mean_height

#1d.
correlation <- cor(df$ShoeSize, df$Height, use = "complete.obs")
print(paste("Correlation between shoe size and height:", correlation))
```


```{r}
#2
monthsvec <- c("March", "April", "Januay", "November", "January", "September", "October", "September", "November", "August", "January", "November", "February", "May", "August", "july", "December", "August", "August", "September", "November", "February", "April")
factor_monthsvec <- factor(monthsvec)

factor_monthsvec

levels(factor_monthsvec)

#3.
summary(monthsvec)

summary(factor_monthsvec)

#4
direction <- c("East", "West", "North")
frequency <- c(1,4,3)
factor_data <- factor(direction, levels = c("East", "West", "North"))
factor_data
new_order_data <- factor(factor_data, levels = c("East", "West", "North"))

```

```{r}
#5
write.csv("import_march.csv", row.names = FALSE)
data <- read.table("import_march.csv", header = TRUE, sep = ",")
data
```

```{r}
#6
exhaustive_search <- function() {
  chosen_number <- sample(1:50, 1)  
  if (chosen_number < 1 || chosen_number > 50) {
    print("The number chosen is beyond the range of 1 to 50")
  } else if (chosen_number == 20) {
    print(TRUE)
  } else {
    print(chosen_number)
  }
}

exhaustive_search()

```

```{r}
#7
price_input <- as.numeric(readline(prompt = "Enter the price of the snack (divisible by 50): "))
## Enter the price of the snack (divisible by 50):
calculate_minimum_bills <- function(price) {
if (is.na(price)) {
cat("Please enter a valid number.\n")
return()
}
if (price %% 50 != 0) {
cat("Price must be a number divisible by 50.\n")
} else {
denominations <- c(1000, 500, 200, 100, 50)
bill_count <- 0
for (denom in denominations) {
if (price >= denom) {
count <- price %/% denom
bill_count <- bill_count + count
price <- price - (count * denom)
}
}
if (bill_count > 0) {
cat("Minimum number of bills needed:", bill_count, "\n")
} else {
cat("No bills needed.\n")
}
}
}
calculate_minimum_bills(price_input) 

```

```{r}
#8
students <- data.frame(
  Names = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85,90)
)
students
#8b.
 for (i in 1:nrow(students)) { avg_score <- (students$Grade1[i] + students$Grade2[i] + students$Grade3[i] + students$Grade4[i]) / 4 
 if (avg_score > 90) { cat(students$Name[i], "'s average grade this semester is", avg_score, "\n")
 } else { cat(students$Name[i], "'s average grade is below 90.\n") } 
 }

#8.c 
for(test in 2:5){
  total_score <- 0 
  num_students <- nrow(students)
for(i in 1:num_students) { 
  total_score <- total_score + students[i, test] } 
  average_score <- total_score / num_students 
if (average_score < 80) { cat("The", test - 1, "test was difficult.\n") 
} else { cat("The", test - 1, "test was not difficult.\n") } 
}

#8d.
for(i in 1:nrow(students)) { 
  highest_score <- 0 
  student_name <- students$Name[i]
for (j in 2:5) {
  if (students[i, j] > highest_score) {
    highest_score <- students[i, j] 
  }
}
  if (highest_score > 90) { 
    cat(student_name, "’s highest grade this semester is", highest_score, ".\n") } 
  }
 

```


